### ISSUE TITLE
Error in cutorch when attempting to train (Ubuntu 16.04)

### ISSUE THREAD

**Issue by thrunq** [jcjohnson/torch-rnn#204]
Hey, I'm a bit of a newbie to all this but I attempted to run train.lua on a script that has been proven to work just fine if run in CPU mode, but for whatever reason when I attempt to run it with CUDA I get the following error:

_THCudaCheck FAIL file=/tmp/luarocks_cutorch-scm-1-3687/cutorch/lib/THC/THCGeneral.c line=70 error=30 : unknown error
/home/coe/torch/install/bin/luajit: /home/coe/torch/install/share/lua/5.1/trepl/init.lua:389: cuda runtime error (30) : unknown error at /tmp/luarocks_cutorch-scm-1-3687/cutorch/lib/THC/THCGeneral.c:70
stack traceback:
	[C]: in function 'error'
	/home/coe/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
	train.lua:55: in main chunk
	[C]: in function 'dofile'
	.../coe/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405d50_

Everything up to this point has installed fine.  Torch and all the deps are there, CUDA is at 7.5, cutorch and cunn seemed to install fine, but I'm not sure what I can do to rectify this issue.  Any help would be greatly appreciated.

**Comment by thrunq** [comment]
Hey guys, sorry for the post.  It turns out that a reboot will fix this issue in case anyone else happens to read this.  Sorry guys.
